=== Erathriel/Pi-Kart_v2/xml/bddSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


    <xsd:element name="id" type="xsd:int"/>

    <xsd:element name="nom" type="xsd:string"/>
     
    <xsd:element name="image" type="xsd:string"/>

    <xsd:element name="type_id" type="xsd:int"/>

    <xsd:element name="forme" type="xsd:string"/>

    <xsd:element name="libelle" type="xsd:string"/>




    <xsd:element name="panneau">

        <xsd:complexType>

        <xsd:sequence>

            <xsd:element ref="id"/>

            <xsd:element ref="nom"/>

            <xsd:element ref="image"/>

            <xsd:element ref="type_id"/>

        </xsd:sequence>

    </xsd:complexType>

    </xsd:element>


        <xsd:element name="typePanneau">

        <xsd:complexType>

        <xsd:sequence>

            <xsd:element ref="id"/>

            <xsd:element ref="forme"/>

            <xsd:element ref="libelle"/>

        </xsd:sequence>

    </xsd:complexType>

    </xsd:element>





  <xsd:element name="Panneaux">

        <xsd:complexType>

            <xsd:sequence>

                <xsd:element ref="panneau" maxOccurs="unbounded" />
         
            </xsd:sequence>

        </xsd:complexType>

    </xsd:element>

    <xsd:element name="typePanneaux">

        <xsd:complexType>

            <xsd:sequence>

                <xsd:element ref="typePanneau" maxOccurs="unbounded" />
         
            </xsd:sequence>

        </xsd:complexType>

    </xsd:element>


  <xsd:element name="BDD">

        <xsd:complexType>

            <xsd:sequence>

                <xsd:element ref="Panneaux" maxOccurs="1" />
                <xsd:element ref="typePanneaux" maxOccurs="1" />
         
            </xsd:sequence>

        </xsd:complexType>

    </xsd:element>


    <xsd:element name="racine">

        <xsd:complexType>

            <xsd:sequence>

                <xsd:element ref="BDD" maxOccurs="1" />
         
            </xsd:sequence>

        </xsd:complexType>

    </xsd:element>

</xsd:schema>

=== Erathriel/Pi-Kart_v2/xml/bdd.xml
<?xml version="1.0" encoding="UTF-8"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="bddSchema.xsd">
        <BDD>
        	<!-- Les panneaux-->
        	<Panneaux>
		        <Panneau>
		              <id> 1 </id>
		              <nom> limitation 30 </nom>
		              <images><img src="images/panneau30.jpg" /></images>
		              <type_id> 1 </type_id>
		        </Panneau>
        	</Panneaux>
        	<!-- Les types de panneaux-->
        	<typePanneaux>
        		<!-- Limitation-->
		        <typePanneau>
			     <id> 1 </id>
			     <forme> circulaire </forme>
			     <libelle> limitation </libelle>
                        </typePanneau>
        		<!-- Danger-->
		        <typePanneau>
		              <id> 2 </id>
		              <forme> triangulaire </forme>
		              <libelle> danger </libelle>
		        </typePanneau>
        		<!-- Arret-->
		        <typePanneau>
		              <id> 3 </id>
		              <forme> hexagonal </forme>
		              <libelle> stop </libelle>
		        </typePanneau>
        		<!-- Indication -->
		        <typePanneau>
		              <id> 4 </id>
		              <forme> carre </forme>
		              <libelle> indication </libelle>
		        </typePanneau>
        		<!-- Obligation-->
		        <typePanneau>
		              <id> 5 </id>
		              <forme> circulaire </forme>
		              <libelle> Obligation </libelle>
		        </typePanneau>
        	</typePanneaux>
        </BDD>
</racine>
