=== Erathriel/Pi-Kart_v2/xml/Type_PanneauxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="idType" type="xsd:int"/>
	<xsd:element name="forme" type="xsd:string"/>
	<xsd:element name="libelle" type="xsd:string"/>
	<xsd:element name="couleur" type="xsd:string"/>

	<xsd:element name="typePanneau">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="idType"/>
				<xsd:element ref="forme"/>
				<xsd:element ref="libelle"/>
				<xsd:element ref="couleur"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="typePanneaux">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="typePanneau" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="BDD">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="typePanneaux" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="racine">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="BDD" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Erathriel/Pi-Kart_v2/xml/Type_Panneaux.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Type_PanneauxSchema.xsd">
        <BDD>
        	<!-- Les types de panneaux -->
        	<typePanneaux>
        		<!-- Limitation -->
        		<typePanneau>
        			<idType> 1 </idType>
        			<forme> circulaire </forme>
        			<libelle> Limitation </libelle>
        			<couleur> Rouge </couleur>
        		</typePanneau>
        		<!-- Danger -->
        		<typePanneau>
        			<idType> 2 </idType>
        			<forme> triangulaire </forme>
        			<libelle> danger </libelle>
        			<couleur> Rouge </couleur>
        		</typePanneau>
        		<!-- Arret -->
        		<typePanneau>
        			<idType> 3 </idType>
        			<forme> hexagonal </forme>
        			<libelle> stop </libelle>
        			<couleur> Rouge </couleur>
        		</typePanneau>
        		<!-- Indication -->
        		<typePanneau>
        			<idType> 4 </idType>
        			<forme> carre </forme>
        			<libelle> indication </libelle>
        			<couleur> Bleu </couleur>
        		</typePanneau>
        		<!-- Obligation -->
        		<typePanneau>
        			<idType> 5 </idType>
        			<forme> circulaire </forme>
        			<libelle> Obligation </libelle>
        			<couleur> Bleu </couleur>
        		</typePanneau>
        		<!-- Interdiction -->
        		<typePanneau>
        			<idType> 6 </idType>
        			<forme> circulaire </forme>
        			<libelle> Obligation </libelle>
        			<couleur > Rouge </couleur>
        		</typePanneau>
        	</typePanneaux>
        </BDD>
</racine>

=== Erathriel/Pi-Kart_v2/Old_Pi_Kart/xml/Type_Panneaux.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<racine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Type_PanneauxSchema.xsd">
        <BDD>
        	<!-- Les types de panneaux -->
        	<typePanneaux>
        		<!-- Limitation -->
        		<typePanneau>
        			<idType>1</idType>
        			<forme>Circulaire</forme>
        			<libelle>Limitation</libelle>
        			<couleur>Rouge</couleur>
        		</typePanneau>
        		<!-- Danger -->
        		<typePanneau>
        			<idType>2</idType>
        			<forme>Triangulaire</forme>
        			<libelle>Danger</libelle>
        			<couleur>Rouge</couleur>
        		</typePanneau>
        		<!-- Arret -->
        		<typePanneau>
        			<idType>3</idType>
        			<forme>Hexagonal</forme>
        			<libelle>Stop</libelle>
        			<couleur>Rouge</couleur>
        		</typePanneau>
        		<!-- Indication -->
        		<typePanneau>
        			<idType>4</idType>
        			<forme>Carre</forme>
        			<libelle>Indication</libelle>
        			<couleur>Bleu</couleur>
        		</typePanneau>
        		<!-- Obligation -->
        		<typePanneau>
        			<idType>5</idType>
        			<forme>circulaire</forme>
        			<libelle>Obligation</libelle>
        			<couleur>Bleu</couleur>
        		</typePanneau>
        		<!-- Interdiction -->
        		<typePanneau>
        			<idType>6</idType>
        			<forme>Circulaire</forme>
        			<libelle>Obligation</libelle>
        			<couleur>Rouge</couleur>
        		</typePanneau>
        	</typePanneaux>
        </BDD>
</racine>
